config/routes.rb
Rails.application.routes.draw do
  resources :employees

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "employees#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :employees, dependent: :destroy

  def self.ransackable_attributes(auth_object = nil)
    %w[name]
  end
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :company

  def self.ransackable_attributes(auth_object = nil)
    %w[first_name last_name phone email birthday country active]
  end

  def self.ransackable_associations(auth_object = nil)
    ["company"]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
# frozen_string_literal: true

# EmployeesController
class EmployeesController < ApplicationController
  include Pagy::Backend
  before_action :set_employee, only: %i[show edit update destroy]

  # GET /employees or /employees.json
  def index
    @q = Employee.ransack(params[:q])
    @employees = @q.result(distinct: true)
    @pagy, @employees = pagy(@q.result.includes(:company))
  end

  # GET /employees/1 or /employees/1.json
  def show; end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit; end

  # POST /employees or /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to employee_url(@employee), notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1 or /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to employee_url(@employee), notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1 or /employees/1.json
  def destroy
    @employee.destroy!

    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_employee
    @employee = Employee.find(params[:id])
  end

  def employee_params
    params.require(:employee).permit(:first_name, :last_name, :phone, :email, :birthday, :country, :active)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
  include Pagy::Frontend
end

app/views/employees/_employee.html.erb
<div id="<%= dom_id employee %>">
  <p>
    <strong>First name:</strong>
    <%= employee.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= employee.last_name %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= employee.phone %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= employee.email %>
  </p>

  <p>
    <strong>Birthday:</strong>
    <%= employee.birthday %>
  </p>

  <p>
    <strong>Country:</strong>
    <%= employee.country %>
  </p>

  <p>
    <strong>Active:</strong>
    <%= employee.active %>
  </p>

</div>

app/views/employees/_form.html.erb
<%= form_with(model: employee) do |form| %>
  <% if employee.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
        <% employee.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :birthday, style: "display: block" %>
    <%= form.date_field :birthday %>
  </div>

  <div>
    <%= form.label :country, style: "display: block" %>
    <%= form.text_field :country %>
  </div>

  <div>
    <%= form.label :active, style: "display: block" %>
    <%= form.check_box :active %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/employees/_results.html.erb
<span><%= Time.zone.now %></span>
<%== pagy_nav(@pagy) %>
<table>
  <thead>
    <tr>
      <th>#</th>
      <th><%= sort_link(@q, :first_name) %></th>
      <th><%= sort_link(@q, :last_name) %></th>
      <th>Phone</th>
      <th><%= sort_link(@q, :email) %></th>
      <th><%= sort_link(@q, :birthday) %></th>
      <th><%= sort_link(@q, :country) %></th>
      <th><%= sort_link(@q, :active) %></th>
      <th><%= sort_link(@q, :company_name, "Company") %></th>
      <th colspan="1">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @employees.each_with_index do |employee, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td><%= highlight employee.first_name, params.dig(:q, :first_name_or_last_name_or_email_or_country_or_company_name_cont) %></td>
        <td><%= highlight employee.last_name, params.dig(:q, :first_name_or_last_name_or_email_or_country_or_company_name_cont) %></td>
        <td><%= employee.phone %></td>
        <td><%= highlight employee.email, params.dig(:q, :first_name_or_last_name_or_email_or_country_or_company_name_cont) %></td>
        <td><%= employee.birthday %></td>
        <td><%= highlight employee.country, params.dig(:q, :first_name_or_last_name_or_email_or_country_or_company_name_cont) %></td>
        <td><%= employee.active %></td>
        <td><%= highlight employee.company.name, params.dig(:q, :first_name_or_last_name_or_email_or_country_or_company_name_cont) %></td>
        <td><%= link_to 'Show', employee, data: { turbo_frame: '_top' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%== pagy_nav(@pagy) %>

app/views/employees/_search_fields.html.erb
<%= f.label :first_name_cont %>
<%= f.search_field :first_name_cont, oninput: 'this.form.requestSubmit();' %> <br>
<%= f.label :last_name_cont %>
<%= f.search_field :last_name_cont, oninput: 'this.form.requestSubmit();' %> <br>
<%= f.label :email_cont %>
<%= f.search_field :email_cont, oninput: 'this.form.requestSubmit();' %> <br>
<%= f.label :birthday_eq %>
<%= f.date_field :birthday_eq, oninput: 'this.form.requestSubmit();' %> <br>
<%= f.label :birthday_gteq %>
<%= f.date_field :birthday_gteq, oninput: 'this.form.requestSubmit();' %> <br>
<%= f.label :birthday_lteq %>
<%= f.date_field :birthday_lteq, oninput: 'this.form.requestSubmit();' %> <br>
<%= f.label :country_eq %>
<%= f.select :country_eq,
  Employee.pluck(:country).uniq.sort,
  {include_blank: true},
  style: 'width: 200px;',
  onchange: 'this.form.requestSubmit();'
%>
<br>
<%#= f.label :company_name_in %>
<%#= f.select :company_name_in, 
  Company.pluck(:name).uniq.sort,
  {include_blank: true, multiple: true},
  style: 'width: 200px;',
  onchange: 'this.form.requestSubmit();' 
%>
<%#= f.collection_check_boxes(:company_name_in, Company.all, :name, :name, {}, onchange: 'this.form.requestSubmit();') %>
<%= f.label :active_eq %>
<%= f.select :active_eq, [true, false], {include_blank: true}, style: 'width: 200px;', onchange: 'this.form.requestSubmit();' %> <br>
<%= f.label :company_name_cont %>
<%= f.search_field :company_name_cont, oninput: 'this.form.requestSubmit();' %> <br>

app/views/employees/_sidebar.html.erb
<label for="active_eq">Active:</label> <hr>
<%= radio_button(:q, :active_eq, nil, onchange: 'this.form.requestSubmit();', form: :search_form) %>
<%= label_tag 'q_active_eq', "All" %> <br>
<%= radio_button(:q, :active_eq, "true", onchange: 'this.form.requestSubmit();', form: :search_form) %>
<%= label_tag 'q_active_eq_true', "Active" %> <br>
<%= radio_button(:q, :active_eq, false, onchange: 'this.form.requestSubmit();', form: :search_form) %>
<%= label_tag 'q_active_eq_false', "Inactive" %>
<br>
<br>
<label for="q_country_eq">Country:</label><br>
<%= select(:q, :country_eq, Employee.pluck(:country).uniq.sort, {include_blank: true}, style: 'width: 200px;', onchange: 'this.form.requestSubmit();', form: :search_form) %>
<br>
<br>
<label for="q_company_name_in">Companies:</label> <hr>
<%= collection_check_boxes(:q, :company_name_in, Company.all, :name, :name, {}, onchange: 'this.form.requestSubmit();', form: :search_form) do |checkbox| %>
  <div>
    <%= checkbox.check_box %>
    <%= checkbox.label %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render "form", employee: @employee %>

<br>

<div>
  <%= link_to "Show this employee", @employee %> |
  <%= link_to "Back to employees", employees_path %>
</div>

app/views/employees/index.html.erb
<h1><%= link_to 'Employees', employees_path %></h1>

<%= search_form_for @q, data: { turbo_frame: :results, turbo_action: 'advance' }, id: :search_form do |f| %>
  <%#= f.label :first_name_or_last_name_or_email_or_country_or_company_name_cont %>
  <%= f.search_field :first_name_or_last_name_or_email_or_country_or_company_name_cont, 
    oninput: 'this.form.requestSubmit();', 
    autofocus: true,
    style: 'width: 100%;',
    placeholder: 'Search'
  %>
  <%#= f.submit %>
<% end %>
<br>
<br>

<div style="display: flex;">
  <div style='width: 300px; border: solid 1px #ddd; padding: 1rem;'>
    <%= render 'sidebar' %>
  </div>
  <div style='margin-left: 1rem; border: solid 1px #ddd; padding: 1rem;'>
    <%= turbo_frame_tag :results, data: { turbo_action: 'advance' } do %>
      <%= render 'results' %>
    <% end %>
  </div>
</div>

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render "form", employee: @employee %>

<br>

<div>
  <%= link_to "Back to employees", employees_path %>
</div>

app/views/employees/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @employee %>

<div>
  <%= link_to "Edit this employee", edit_employee_path(@employee) %> |
  <%= link_to "Back to employees", employees_path %>

  <%= button_to "Destroy this employee", @employee, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DataTablesHotwired</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <h1><%= Time.zone.now %></h1>
    <%= yield %>
  </body>
</html>